### ISSUE TITLE
프로젝트 초기 세팅

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#1]
## Description

- 프로젝트 초기 세팅

## To-do

- [x] React Native CLI ios 시작
- [x] PR, Issue 템플릿 셋팅
- [x] 스토리북 셋팅
- [ ] 라이브러리 셋팅
- [ ] 네비게이션 관련 셋팅
