### ISSUE TITLE
[FEAT] 메인화면 - 푸시 알림 스크린 추가

### ISSUE THREAD

**Issue by minimalKim** [dnd-side-project/dnd-9th-9-frontend#107]
## Description
- 푸시 알림 스크린을 추가합니다.

![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/120aa515-10c4-40e6-a34e-e330478a80ee)

## To-do

- [ ] 푸시 알림 스크린 및 컴포넌트 추가
- [ ] FlatList 사용 및 무한 스크롤 구현
- [ ] 관련 api 추가 및 연동
