### ISSUE TITLE
[FEAT] 매칭 팀 상세 정보 및 가입하기

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#13]
## Description

- 매칭 팀 상세 정보 및 가입하기
<img width="798" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/97efa1dc-2cac-4d8b-9955-9103c2df991a">

## To-do

- 팀 상세 화면
  - [x] 팀 프로필 정보
  - [x] 팀 기록 정보 (권한)
  - [x] 팀 매칭 정보 (권한)
  - [x] 팀원 정보 

- 팀원 모집 중인 경우 
  - [x] 팀원 신청 
    - [ ] 신청 취소 기능
  - [x] 팀 나가기 기능 (권한)

- 팀원 모집 완료인 경우
  - [x] 매칭 신청 기능
