### ISSUE TITLE
[FEAT] 팀 상세 페이지 (기록 메인)

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#29]
## Description

- 팀 상세 페이지 (기록 탭)

<img width="442" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/51541200-6245-464a-adfb-09283258b3df">

## To-do

- 기록 default
  - [x] 캘랜더 선택 날짜 별 기록 스레드 기능
  - [x] 자동 슬라이드 UI (15s마다 옆으로 움직여서 승부, 디데이, 규칙 보여주기) 
  - [ ] 팀원 깨우기 기능

## ETC

- 1:1 매칭과 다른 부분 체크하기
