### ISSUE TITLE
[FEAT] 팀 상세 페이지 (매칭 안된 상태)

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#30]
## Description

- 팀 상세 매칭 탭 (매칭 안된 상태)

| 매칭탭 목록 | 신청한 매칭 | 요청받은 매칭 |
| ----- | ----- | ----- |
| <img width="305" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/5a043174-9693-4652-9191-9aa38e93295f"> | <img width="812" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/2884151b-15ed-4e3f-bced-db4c748b224a"> | <img width="866" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/98f867bd-447b-4806-a917-5ad66024ab0c"> |

## To-do

- 매칭탭 목록
  - [x] 신청한 매칭 목록 (3개 이상인 경우 더보기 활성화)
  - [x] 요청받은 매칭 목록 (3개 이상인 경우 더보기 활성화)

- 신청한 매칭 상세 (팀장만 기능 사용 가능, 목록 확인 팀원도 가능)
  - [x] 더보기 목록
  - [ ] 상대 팀 프로필에서 매칭 신청 취소 기능
  - [x] 매칭 신청 취소 다중 선택 기능

- 요청받은 매칭 상세 (팀장만 기능 사용 가능, 목록 확인 팀원도 가능)
  - [x] 더보기 목록
  - [ ] 상대 팀 프로필에서 매칭 수락 기능
  - [x] 매칭 수락 선택 기능 (`매칭 거절 기능은 보류하기로 함`)

## ETC

- 1:1 매칭 고려하여 작업
