### ISSUE TITLE
[FEAT] 팀 상세 페이지 (팀원) 

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#31]
## Description

<img width="798" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/d21c9127-87e1-4e00-aec8-6c2693e98b28">

<img width="531" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/e5652a6f-21e9-4fb0-863f-57ff69b2bae9">

<img width="840" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/a3425bfa-e894-4223-ba7f-5e2b2239af11">

## To-do

- [ ] 현재 팀원 및 요청 목록 보기

- 방장
  - [ ] 팀 나가기
  - [ ] 방장 넘기기
  - [ ] 현재 팀원 삭제 
  - [ ] 요청 팀원 수락, 거절

- 팀원
  - [ ] 팀 나가기

## ETC

- 1:1 에서도 필요한 기능인지 검토해보는 중
