### ISSUE TITLE
[FEAT] 팀 상세 페이지 (매칭 종료)

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#32]
## Description

- 매칭 종료 Feature 작업을 진행합니다.

| 매칭 팀워크 평가 | 매칭 결과 | 매칭 종료 후 카드 및 상세 화면 |
|--------|--------|--------|
| ![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/d2ad884f-2dce-48e8-9916-8cd907f5fef9)| ![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/6ded396a-e7e8-46ce-b4f6-e989d7f5df4b) |  ![image](https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/ee539928-f1d0-4f9d-bf6c-71d1e100eb0b) |

## To-do

- [x] 매칭 결과 및 팀워크 평가 기능
- [x] 팀별 결과 비교 (운동시간, 칼로리, 기록횟수, 목표달성횟수)
- [x] 매칭 결과 확인 기능
  - 뱃지 기능 (2개 이상일 경우 스켈레톤) -> 현재 버전에서 작업하지 않는 것으로 픽스

## ETC

- 개인 대결의 경우 평가 기능 X
