### ISSUE TITLE
[FEAT] 플로팅을 통한 자동 매칭 

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#33]
## Description

- 자동 매칭
<img width="909" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/4a457bde-5fd3-4eaf-870c-b3442c70b49a">

## To-do

- [x] 플로팅 UI
- [x] 자동 매칭 찾기 로딩 기능
- [x] 자동 매칭 다시 찾기, 신청하기 
- [x] 조건 없음 화면
