### ISSUE TITLE
[FEAT] MY 매칭 - 신청, 진행중, 진행 완료 매칭 목록

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#34]
## Description

<img width="595" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/9ac4214f-f9be-4ec0-a010-d6657bfb012c">

<img width="657" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/57554421/7eec86b0-ff23-4bcc-a9c5-440418be4679">

- My 매칭 화면 관련한 기능을 작업합니다.
  - 신청, 진행중, 진행완료한 매칭 목록을 제공합니다.
  - 각 매칭 클릭시, 상세 화면으로 navigate 이동합니다.

## To-do

- [ ] 진행 완료 목록에 대한 필터 기능
- [x] 상세 프로필 바로가기 기능
- [x] 신청, 진행 중, 진행 완료 목록 API 연동
  - [x]  `GET /field-entry` : 신청한 내역 조회
  - [x]  `GET /user-field/progress` : 진행 중인 나의 필드 조회
  - [x]  `GET /user-field/completed` : 종료된 나의 필드 조회
