### ISSUE TITLE
[FEAT] 인증 - 일반 회원가입 - 유저 개인정보 입력 구현

### ISSUE THREAD

**Issue by minimalKim** [dnd-side-project/dnd-9th-9-frontend#83]
## Description
- 일반 회원가입 기능을 구현합니다. (운동 경력 제외)
<img width="789" alt="image" src="https://github.com/dnd-side-project/dnd-9th-9-frontend/assets/80511900/0896ea67-5ebf-45ba-bb7b-28945e86114b">

## To-do

- [ ] 아이디 - 아이디 유효성 검증
- [ ] 아이디 - 사용중인 아이디 검증 
- [ ] 전화번호 - 전화번호 유효성 검증 // 인증 번호 관련 기능은 백엔드 구현 후 연동 예정
- [ ] 비밀번호 - 비밀번호 유효성 검증
- [ ] 비밀번호 - 비밀번호 확인 일치 검증
