### ISSUE TITLE
[FEAT] 매칭 상세 매칭탭 - API 연동

### ISSUE THREAD

**Issue by chajuhui123** [dnd-side-project/dnd-9th-9-frontend#93]
## Description

- 매칭 상세 매칭탭에 대하여 API 연동 작업을 진행합니다.

## To-do

- [x]  보기 권한은 MEMBER도 존재하는데, 신청 취소, 필드 수락은 LEADER만 가능
- [x]  신청한 매칭 관련 API 연동
    - `GET /field-entry/battle/{id}` : 배틀 신청 내역 조회 (EntryDirection=’SENT’)
    - `DELETE /field-entry/{id}` : 필드 신청 취소
- [x]  요청받은 매칭 관련 API 연동
    - `GET /field-entry/battle/{id}` : 배틀 신청 내역 조회 (EntryDirection=’RECEIVED’)
    - `POST /field-entry/{id}/accept` : 필드 수락
